### ISSUE TITLE
StateClass measurment missing in MQTT autodiscovery

### ISSUE THREAD

**Issue by chriszuercher** [nplan/HomeButtons#82]
I found, that the sensors created in HomeAssistant are missign the state_class: measurement setting,. This means the entities have no longe term statistics. 

I could override the entities in my config with this:

```yaml
homeassistant:
  customize:
    # Add an entry for each entity that you want to overwrite.
    sensor.home_buttons_ID_temperature:
        state_class: measurement
    sensor.home_buttons_ID_humidity:
        state_class: measurement

```

But I think it could be fixed by adding 

`conf["stat_cla"] = "measurement";`

to the respective sensor.
